"use client";

/**
 * src/hooks/useUploadQuotePdf.ts
 *
 * Encapsulates the complete "upload PDF blob → patch DB record" flow so
 * QuoteSheet stays focused on UI concerns.
 *
 * FLOW
 * ────
 *   1. Caller passes the raw PDF Blob (already generated by @react-pdf/renderer)
 *      and the quoteId returned by saveQuoteAction.
 *   2. The hook converts the Blob to a File (UploadThing requires a File).
 *   3. startUpload() sends the file to UploadThing via the quotePdf route.
 *   4. onClientUploadComplete fires with { ufsUrl, key } from the server.
 *   5. updateQuotePdfAction patches the Quote record in the DB.
 *
 * ERROR HANDLING
 * ──────────────
 * Upload errors and DB patch errors are surfaced separately via the returned
 * `error` state and toasts so the user knows whether the download succeeded
 * even if the cloud backup failed (non-blocking from UX perspective).
 *
 * USAGE in QuoteSheet
 * ───────────────────
 *   const { uploadPdf, isUploading, uploadError } = useUploadQuotePdf();
 *
 *   // After saveQuoteAction resolves and the browser download is triggered:
 *   await uploadPdf({ blob: pdfBlob, quoteId, fileName });
 */

import { useState } from "react";
import { toast } from "sonner";
import { useUploadThing } from "uploadthing/react";
import { updateQuotePdfAction } from "@/actions/quotes.action";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface UploadPdfParams {
  blob: Blob;
  quoteId: string;
  fileName: string; // e.g. "FQ-2025-48291_acme_corp.pdf"
}

interface UseUploadQuotePdfReturn {
  uploadPdf: (params: UploadPdfParams) => Promise<void>;
  isUploading: boolean;
  uploadError: string | null;
}

// ---------------------------------------------------------------------------
// Hook
// ---------------------------------------------------------------------------

export function useUploadQuotePdf(): UseUploadQuotePdfReturn {
  const [isUploading, setIsUploading] = useState(false);
  const [uploadError, setUploadError] = useState<string | null>(null);

  const { startUpload } = useUploadThing("quotePdf", {
    onUploadError: (err) => {
      console.error("UploadThing error:", err);
      setUploadError(err.message);
      toast.error("PDF could not be backed up to cloud.");
      setIsUploading(false);
    },
  });

  const uploadPdf = async ({
    blob,
    quoteId,
    fileName,
  }: UploadPdfParams): Promise<void> => {
    setIsUploading(true);
    setUploadError(null);

    try {
      // UploadThing requires a File, not a Blob
      const file = new File([blob], fileName, { type: "application/pdf" });

      const result = await startUpload([file]);

      if (!result || result.length === 0) {
        throw new Error("Upload returned no result.");
      }

      const { ufsUrl, key } = result[0] as { ufsUrl: string; key: string };

      // Patch the DB record with the CDN URL
      const patchResult = await updateQuotePdfAction({
        quoteId,
        pdfUrl: ufsUrl,
        pdfKey: key,
      });

      if (!patchResult.success) {
        // Upload succeeded but DB patch failed — not ideal but the file is
        // safely on UploadThing. Log and surface a warning rather than an error.
        console.warn("updateQuotePdfAction failed after successful upload");
        toast.warning("PDF uploaded but link could not be saved. Contact support if needed.");
        return;
      }

      toast.success("PDF saved to cloud.");
    } catch (err) {
      const message =
        err instanceof Error ? err.message : "Unknown upload error.";
      setUploadError(message);
      toast.error("PDF backup failed.");
    } finally {
      setIsUploading(false);
    }
  };

  return { uploadPdf, isUploading, uploadError };
}